<?php require './templates/header.phtml' ?>

<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Fecha de creación</th>
            <th scope="col">Origen</th>
            <th scope="col">Edición</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($devs as $dev): ?>
        <tr>
            <td><?= $dev->nombreDesarrollador ?></td>
            <td><?= $dev->fechaCreacion ?></td>
            <td><?= $dev->origen ?></td>
            <td><button class="btn btn-warning">Editar</button><button class="btn btn-danger">Borrar</button></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>


<?php require './templates/footer.phtml' ?>