<?php require './templates/header.phtml' ?>

<div class='detalles-desarrolladores'>
    <a href='add-developer' class='btn btn-success'>+ Agregar</a>
</div>

<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Fecha de creación</th>
            <th scope="col">Origen</th>
            <th scope="col">Edición</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($devs as $dev): ?>
        <tr>
            <td><?= $dev->nombreDesarrollador ?></td>
            <td><?= $dev->fechaCreacion ?></td>
            <td><?= $dev->origen ?></td>
            <td><a class="btn btn-warning">Editar</a><a href='delete-dev/<?= $dev->desarrolladorId ?>' class="btn btn-danger">Borrar</a></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>


<?php require './templates/footer.phtml' ?>