<?php require './templates/header.phtml' ?>

<div class='filtros-juegos'>
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" data-bs-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
        Filtrar por desarrollador
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <?php foreach($devs as $dev): ?>
        <a class="dropdown-item" href="games/developer/<?= $dev->id ?>"><?= $dev->nombreDesarrollador ?></a>
        <?php endforeach ?>
    </div>
    <div>
        <a href='add-game' class='btn btn-success'>+ Agregar</a>
    </div>
</div>

<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Desarrollador</th>
            <th scope="col">Fecha de lanzamiento</th>
            <th scope="col">Edad mínima</th>
            <th scope="col">Edición</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($games as $game): ?>
        <tr>
            <td><a class="link-underline link-underline-opacity-0" href='game/<?= $game->id ?>'><?= $game->nombreJuego ?></a></td>
            <td><?= $game->nombreDesarrollador ?></td>
            <td><?= $game->fechaLanzamiento ?></td>
            <td><?= $game->edad ?></td>
            <td><button class="btn btn-warning">Editar</button><button class="btn btn-danger">Borrar</button></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>


<?php require './templates/footer.phtml' ?>