<?php require './templates/header.phtml' ?>

<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Desarrollador</th>
            <th scope="col">Fecha de lanzamiento</th>
            <th scope="col">Edad mínima</th>
            <th scope="col">Edición</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($games as $game): ?>
        <tr>
            <td><?= $game->nombreJuego ?></td>
            <td><?= $game->nombreDesarrollador ?></td>
            <td><?= $game->fechaLanzamiento ?></td>
            <td><?= $game->edad ?></td>
            <td><button class="btn btn-warning">Editar</button><button class="btn btn-danger">Borrar</button></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>


<?php require './templates/footer.phtml' ?>